version: '3'

services:
    workspace:
        image: base-workspace
        volumes:
            - "${WSHELL_DIR}:/var/www/wshell"
        ports:
            - "8080:8080"
        tty: true
    web:
        image: base-nginx
        volumes:
            - "./wshell.conf:/etc/nginx/conf.d/default.conf"
            - "${WSHELL_DIR}:/var/www/wshell"
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=wshell.local
        command: ['nginx', '-g', 'daemon off;']
        restart: always
        depends_on:
            - php
    php:
        image: base-php-full
        restart: always
        volumes:
            - "${WSHELL_DIR}:/var/www/wshell"
    composer:
        image: base-alpine-composer
        volumes:
            - "${WSHELL_DIR}:/app"
        command: install --ignore-platform-reqs
